### ISSUE TITLE
Failed to register a ServiceWorker on demo

### ISSUE THREAD

**Issue by xdumaine** [bahmutov/bottle-service#11]
When I load https://glebbahmutov.com/bottle-service/

I get the error: `bottle service error DOMException: Failed to register a ServiceWorker: The path of the provided scope ('/') is not under the max scope allowed ('/bottle-service/'). Adjust the scope, move the Service Worker script, or use the Service-Worker-Allowed HTTP header to allow the scope.`

**Comment by bahmutov** [comment]
Yup, the scope is wrong, use the demo link https://bottle-service.herokuapp.com/ for now - I will adjust the source for the app to work at both later

**Comment by xdumaine** [comment]
Ahh, cool, I was guessing at the demo link based on the repo. Missed it in the readme. Thanks.

**Comment by xdumaine** [comment]
@bahmutov have you been able to get this to work on localhost with a self-signed cert? Chrome is supposed to treat localhost as secure, but i'm getting this 
![screen shot 2015-12-30 at 2 04 08 pm](https://cloud.githubusercontent.com/assets/833911/12055781/6c58a934-aefe-11e5-849f-7285cc4eacfb.png)

**Comment by bahmutov** [comment]
Have not tried local https, but it should just work from http localhost

**Comment by xdumaine** [comment]
Looks like it's due to [this chrome bug](https://code.google.com/p/chromium/issues/detail?id=561820).

**Comment by bahmutov** [comment]
weird, I have not encountered any problems with Chrome / Chrome Canary / Opera locally or at heroku, but I am not running local certificate server either
