### ISSUE TITLE
Allow use on non root pages

### ISSUE THREAD

**Issue by xdumaine** [bahmutov/bottle-service#12]
First off - wow! thanks for making this repo. This is awesome, and I'm definitely willing to put some effort into fixing these things I'm reporting. 

The current implementation prevents the service worker from caching pages like `http://example.com/myapp` since it always checks for the root page `http://example.com`

One idea to do this - check the full URL when calling `refill` and storing it with the cache, and allowing the matching request to load from cache.

**Comment by bahmutov** [comment]
yeah, it is limited in its scope - and this even limits from demoing it on my own website glebbahmutov.com/bottle-serve for example. I need to think what makes sense here
