### ISSUE TITLE
Don't require element matching element to be div with opening/closing id

### ISSUE THREAD

**Issue by xdumaine** [bahmutov/bottle-service#13]
Currently, the service worker looks specifically for a `div` tag with an `id` set on both the opening and closing tag, and cannot have any other properties (like classes) Ideally, this would work with _any_ element, with or without additional attributes, and without an `id` on the closing tag. 

One idea: create an html element from the string, and then query that element. I'm not sure how much of that is possible in service worker context though.

**Comment by bahmutov** [comment]
yeah, the query is the hard part ;) Basically I need to find **small** HTML parsing library to be able to find the element to update.
